version: '3.3'

services:
  traefik:
    image: traefik:1.7.16
    ports:
      - '80:80'
      - '443:443'
      - '8090:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/acme.json:/acme.json
    configs:
      - source: traefik.{{ts}}
        target: /etc/traefik/traefik.toml
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - overlay_net

  api:
    secrets:
      - jwt-public-key.{{ts}}
    environment:
      - CERT_PUBLIC_KEY_PATH=/run/secrets/jwt-public-key.{{ts}}
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.frontend.rule=Host: mosip.{{hostname}}'
        - 'traefik.port=4545'
        - 'traefik.docker.network=opencrvs_overlay_net'
      replicas: 2
    networks:
      - overlay_net

secrets:
  jwt-public-key.{{ts}}:
    external: true
  jwt-private-key.{{ts}}:
    external: true

configs:
  traefik.{{ts}}:
    file: ./infrastructure/traefik.toml

networks:
  overlay_net:
    driver: overlay
    attachable: true
